package unit.status;

public enum StatusType {
	FIXED_POW, FLOAT_POW, FIXED_INT, FLOAT_INT, FIXED_AGI, FLOAT_AGI,
	RED_BAR, BLUE_BAR, GREEN_BAR, WHITE_BAR,
	RED_REG, BLUE_REG, GREEN_REG,
	SPEED,
	SENSE,
	WEIGHT,
	TOUGHNESS, TOUGHNESS_REG,
	CRI, AVD, REF, SUCK,
}
